### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by AJKBajwa** [ldab/ESP32-CAM-MQTT#2]
My ESP does not connect to the MQTT client. Can you provide more details about setting the credentials and how to set up cloud MQTT.

**Comment by ldab** [comment]
You just need to create your broker at CloudMQTT and use the credentials they provide, for example:

![Annotation 2019-09-19 201216](https://user-images.githubusercontent.com/34199302/65269663-f013b700-db19-11e9-8fa7-1e750e33a9c8.png)
