### ISSUE TITLE
LDO, new option ME6211, TYP. 40 uA

### ISSUE THREAD

**Issue by tonilopezortiz78** [ldab/ESP32-CAM-MQTT#4]
https://stm32-base.org/assets/pdf/regulators/ME6211.pdf

**Comment by ldab** [comment]
I don't manufacture the board, not sure what you mean with the comment.

**Comment by tonilopezortiz78** [comment]
Sorry, I'm new with GitHub, just I saw in readme a comment about the LDO use 6mA in sleep mode that is a lot for sleep mode, just I bring information about and LDO that only use 40uA = 0.040mA. it is just a comment

Sent from Yahoo Mail on Android 
 
  On Fri, Jul 24, 2020 at 15:46, Leonardo Bispo<notifications@github.com> wrote:   


I don't manufacture the board, not sure what you mean with the comment.
