### ISSUE TITLE
Publishing UXGA picture isn't working

### ISSUE THREAD

**Issue by marioqqq** [ldab/ESP32-CAM-MQTT#5]
I use your src code to publish picture into Rpi. When I use QQVGA, everything works fine, but image resolution is not suitable for processing. So I tried UXGA, program runs 2-4 times before it is successful, but image was not received by Rpi. 
![Capture](https://user-images.githubusercontent.com/93001533/138490631-e26fa655-048d-4723-861b-d52634b86847.PNG)

**Comment by ldab** [comment]
It’s likely to be memory related, check `ESP.getFreeHeap()`

also try to decode the dump: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#register-dump-and-backtrace
